Repository bmish/eslint-doc-generator, pull requests merged in 2022-10, with the labels that each got.

#5 Add missing Node shebang to binary
  bin/eslint-doc-generator.ts
Labels: bug

#6 Move emojis into centralized file
  lib/emojis.ts
  lib/rule-list.ts
  lib/rule-notices.ts
Labels: internal

#7 Use recommended config emoji in rules list header when no custom configs present
  README.md
  lib/rule-list.ts
  test/lib/__snapshots__/generator-test.ts.snap
Labels: documentation

#8 Use `recommended` config emoji in rule doc when rule is only in that config
  lib/configs.ts
  lib/rule-list.ts
  lib/rule-notices.ts
  test/lib/__snapshots__/generator-test.ts.snap
  test/lib/generator-test.ts
Labels: documentation

#11 Provide rule list comment markers in error message when missing from README
  lib/rule-list.ts
  test/lib/__snapshots__/generator-test.ts.snap
  test/lib/generator-test.ts
Labels: documentation

#12 When rule doc is missing marker comment, remove old title before adding new one
  lib/generator.ts
  test/lib/__snapshots__/generator-test.ts.snap
  test/lib/generator-test.ts
Labels: bug

#17 Automatically insert missing rule list markers in README rules section
  lib/rule-list.ts
  test/lib/__snapshots__/generator-test.ts.snap
  test/lib/generator-test.ts
Labels: bug

#18 Allow deprecated rules to forgo a doc file or description
  lib/generator.ts
  test/lib/__snapshots__/generator-test.ts.snap
  test/lib/generator-test.ts
Labels: bug

#19 Tweak README
  README.md
Labels: documentation

#28 Use prettier's own config resolution when formatting docs
  lib/generator.ts
  lib/package-json.ts
  test/lib/generator-test.ts
Labels: bug

#39 Add plugin prefix to rule name in rule doc title
  lib/rule-notices.ts
  test/lib/__snapshots__/generator-test.ts.snap
Labels: bug

#40 Description in rule doc title should begin with a capital letter and omit a trailing period
  lib/rule-notices.ts
  test/lib/__snapshots__/generator-test.ts.snap
  test/lib/generator-test.ts
Labels: bug

#41 Handle scoped plugin names
  jest.config.cjs
  lib/package-json.ts
  test/lib/__snapshots__/generator-test.ts.snap
  test/lib/generator-test.ts
Labels: bug

#42 Allow plugin to omit configs
  lib/rule-list.ts
  test/lib/__snapshots__/generator-test.ts.snap
  test/lib/generator-test.ts
Labels: bug

#43 Improved detection for README rules section when marker comments are missing
  lib/rule-list.ts
  test/lib/rules-list-test.ts
Labels: bug

#45 Handle various possible names for options section when checking for its presence in rule doc
  lib/generator.ts
  test/lib/generator-test.ts
Labels: bug

#47 Throw exception when plugin does not export a `rules` object
  lib/package-json.ts
  test/lib/__snapshots__/generator-test.ts.snap
  test/lib/generator-test.ts
Labels: bug

#48 Only apply prettier formatting to managed doc content
  .eslintrc.cjs
  lib/generator.ts
  lib/markdown.ts
  lib/rule-list.ts
  lib/rule-notices.ts
  test/lib/__snapshots__/generator-test.ts.snap
  test/lib/generator-test.ts
Labels: bug

#59 Resolve `extends` in ESLint configs
  jest.config.cjs
  lib/config-resolution.ts
  lib/configs.ts
  lib/generator.ts
  lib/rule-list.ts
  lib/rule-notices.ts
  lib/types.ts
  test/lib/__snapshots__/generator-test.ts.snap
  test/lib/generator-test.ts
Labels: bug

#60 Ignore external configs during ESLint config resolution
  lib/config-resolution.ts
  test/lib/generator-test.ts
Labels: bug

#62 Fix plugin importing on Windows
  lib/config-resolution.ts
  lib/import.ts
  lib/package-json.ts
Labels: bug

#65 Handle config overrides
  jest.config.cjs
  lib/config-resolution.ts
  lib/types.ts
  test/lib/__snapshots__/generator-test.ts.snap
  test/lib/generator-test.ts
Labels: bug

#67 Handle rule enabled with options
  lib/configs.ts
  lib/types.ts
  test/lib/__snapshots__/generator-test.ts.snap
  test/lib/generator-test.ts
Labels: bug

#70 Handle string `extends` from ESLint config, deprecated/function-style rules, missing rule descriptions (and use actual ESLint types to detect issues like these)
  lib/config-resolution.ts
  lib/generator.ts
  lib/package-json.ts
  lib/rule-list.ts
  lib/rule-notices.ts
  lib/types.ts
  test/lib/__snapshots__/generator-test.ts.snap
  test/lib/generator-test.ts
Labels: bug

#72 Improve section header detection
  lib/markdown.ts
  test/lib/markdown-test.ts
Labels: bug

#73 Hide config column from rules list when no configs present and move deprecations to a separate column
  lib/configs.ts
  lib/rule-list.ts
  test/lib/__snapshots__/generator-test.ts.snap
  test/lib/generator-test.ts
Labels: enhancement

#75 Automatically generate legend for rules list
  README.md
  lib/legend.ts
  lib/rule-list-columns.ts
  lib/rule-list.ts
  test/lib/__snapshots__/generator-test.ts.snap
Labels: enhancement

#76 Hide empty columns from rules list
  lib/generator.ts
  lib/legend.ts
  lib/rule-list-columns.ts
  lib/rule-list.ts
  test/lib/__snapshots__/generator-test.ts.snap
  test/lib/generator-test.ts
Labels: enhancement

#74 Tweak README
  README.md
Labels: documentation

#80 Throw error when missing rule doc
  lib/generator.ts
  lib/package-json.ts
  test/lib/generator-test.ts
Labels: bug

#81 Throw error when missing README.md
  lib/generator.ts
  test/lib/generator-test.ts
Labels: bug

#82 Add `--url-configs` option
  README.md
  lib/cli.ts
  lib/generator.ts
  lib/legend.ts
  lib/rule-list-columns.ts
  lib/rule-list.ts
  lib/rule-notices.ts
  test/lib/__snapshots__/generator-test.ts.snap
  test/lib/generator-test.ts
Labels: enhancement

#83 Add `--rule-doc-title-format` option
  README.md
  lib/cli.ts
  lib/generator.ts
  lib/rule-doc-title-format.ts
  lib/rule-notices.ts
  test/lib/__snapshots__/generator-test.ts.snap
  test/lib/generator-test.ts
Labels: enhancement

#84 Add `--rule-doc-section-include` and `--rule-doc-section-exclude` options
  README.md
  lib/cli.ts
  lib/generator.ts
  package.json
  test/lib/generator-test.ts
Labels: enhancement

#87 Handle when prettier is not installed
  lib/markdown.ts
  lib/rule-list.ts
  lib/rule-notices.ts
  package.json
  test/lib/__snapshots__/generator-test.ts.snap
  test/lib/generator-test.ts
Labels: bug

#92 Add `--ignore-deprecated-rules` option
  README.md
  lib/cli.ts
  lib/generator.ts
  test/lib/__snapshots__/generator-test.ts.snap
  test/lib/generator-test.ts
Labels: enhancement

#93 Add `--ignore-config` option
  README.md
  lib/cli.ts
  lib/configs.ts
  lib/generator.ts
  lib/rule-list-columns.ts
  lib/rule-list.ts
  lib/rule-notices.ts
  test/lib/__snapshots__/generator-test.ts.snap
  test/lib/generator-test.ts
Labels: enhancement

#101 Improve notice/legend wording consistency and conciseness
  README.md
  lib/legend.ts
  lib/rule-notices.ts
  test/lib/__snapshots__/generator-test.ts.snap
Labels: bug

#102 Use `Name` instead of `Rule` for rule list column header
  lib/rule-list-columns.ts
  test/lib/__snapshots__/generator-test.ts.snap
Labels: bug

#103 Left-align rule list column headers
  README.md
  lib/rule-list.ts
  test/lib/__snapshots__/generator-test.ts.snap
Labels: bug

#104 Add `desc` format to `--rule-doc-title-format` option
  README.md
  lib/rule-doc-title-format.ts
  lib/rule-notices.ts
  test/lib/__snapshots__/generator-test.ts.snap
  test/lib/generator-test.ts
Labels: enhancement

#106 Handle lowercase `readme.md`
  lib/generator.ts
  lib/package-json.ts
  lib/rule-list.ts
  test/lib/__snapshots__/generator-test.ts.snap
  test/lib/generator-test.ts
Labels: bug

#108 Improve README especially about config options
  README.md
  lib/cli.ts
  lib/generator.ts
Labels: documentation

#109 Add `--check` option
  README.md
  lib/cli.ts
  lib/generator.ts
  test/lib/__snapshots__/generator-test.ts.snap
  test/lib/generator-test.ts
Labels: enhancement

#116 Add `--config-emoji` option
  README.md
  lib/cli.ts
  lib/configs.ts
  lib/generator.ts
  lib/legend.ts
  lib/rule-list-columns.ts
  lib/rule-list.ts
  lib/rule-notices.ts
  lib/types.ts
  test/lib/__snapshots__/generator-test.ts.snap
  test/lib/generator-test.ts
Labels: enhancement

#118 Tweak fixable documentation link
  README.md
  lib/legend.ts
  lib/rule-notices.ts
  test/lib/__snapshots__/generator-test.ts.snap
Labels: bug

#119 Tweak readme examples
  README.md
Labels: documentation

#125 Tweak suggestions documentation link
  README.md
  lib/legend.ts
  lib/rule-notices.ts
  test/lib/__snapshots__/generator-test.ts.snap
Labels: bug

#126 Add rule doc notice when type-checking is required
  lib/rule-notices.ts
  test/lib/__snapshots__/generator-test.ts.snap
  test/lib/generator-test.ts
Labels: enhancement

#127 Refactor to ensure a rule doc notice is defined for each column type
  lib/rule-notices.ts
Labels: internal

#129 Add `--rule-list-columns` option
  README.md
  lib/cli.ts
  lib/configs.ts
  lib/generator.ts
  lib/rule-list-columns.ts
  lib/rule-list.ts
  test/lib/__snapshots__/generator-test.ts.snap
  test/lib/generator-test.ts
Labels: enhancement

#130 Add motivation section to README
  README.md
Labels: documentation

#131 Separate column type presence and ordering
  lib/cli.ts
  lib/rule-list-columns.ts
Labels: internal

#134 Add optional column and notice for rule type
  README.md
  lib/cli.ts
  lib/emojis.ts
  lib/generator.ts
  lib/legend.ts
  lib/rule-list-columns.ts
  lib/rule-list.ts
  lib/rule-notices.ts
  lib/rule-type.ts
  lib/types.ts
  test/lib/__snapshots__/generator-test.ts.snap
  test/lib/generator-test.ts
Labels: enhancement

#136 Add default emojis for common configs
  README.md
  lib/configs.ts
  lib/emojis.ts
  lib/legend.ts
  lib/rule-list-columns.ts
  lib/rule-list.ts
  lib/rule-notices.ts
  test/lib/__snapshots__/generator-test.ts.snap
  test/lib/generator-test.ts
Labels: enhancement

#137 Support removing the default emoji for a config with `--config-emoji` option
  README.md
  lib/configs.ts
  test/lib/__snapshots__/generator-test.ts.snap
  test/lib/generator-test.ts
Labels: enhancement

#139 Add `--rule-doc-notices` option
  README.md
  lib/cli.ts
  lib/generator.ts
  lib/legend.ts
  lib/options.ts
  lib/rule-list-columns.ts
  lib/rule-list.ts
  lib/rule-notices.ts
  lib/types.ts
  test/lib/__snapshots__/generator-test.ts.snap
  test/lib/generator-test.ts
Labels: enhancement

#147 Hide ignored configs from rule list legend
  lib/legend.ts
  test/lib/generator-test.ts
Labels: bug

#148 Avoid wrapping name column in rules list
  lib/legend.ts
  lib/rule-list-columns.ts
  lib/rule-list.ts
  lib/rule-notices.ts
  test/lib/__snapshots__/generator-test.ts.snap
  test/lib/generator-test.ts
Labels: bug

#149 Add consolidated rule doc notice for fixable and suggestions
  README.md
  lib/rule-notices.ts
  lib/types.ts
  test/lib/__snapshots__/generator-test.ts.snap
Labels: enhancement

#152 Use markdown-table for generating rules list
  lib/rule-list.ts
  package-lock.json
  package.json
Labels: bug

#153 Avoid two config legends for the same emoji
  lib/legend.ts
  test/lib/__snapshots__/generator-test.ts.snap
  test/lib/generator-test.ts
Labels: bug

#154 Use code styling for replacement rule name in deprecated rule notice
  lib/rule-notices.ts
  test/lib/__snapshots__/generator-test.ts.snap
Labels: bug

#155 Indicate that content is auto-generated in marker comments
  README.md
  lib/markers.ts
  test/lib/__snapshots__/generator-test.ts.snap
  test/lib/generator-test.ts
Labels: breaking

#156 Indicate which configs disable a rule
  lib/configs.ts
  lib/legend.ts
  lib/rule-list.ts
  lib/rule-notices.ts
  lib/types.ts
  test/lib/__snapshots__/generator-test.ts.snap
  test/lib/generator-test.ts
Labels: enhancement

#158 Fix ts-jest deprecation warning
  jest.config.cjs
Labels: internal

#161 Fix script in README
  README.md
Labels: documentation

#162 Add `--split-by` option
  README.md
  lib/cli.ts
  lib/generator.ts
  lib/rule-list.ts
  package-lock.json
  package.json
  test/lib/__snapshots__/generator-test.ts.snap
  test/lib/generator-test.ts
Labels: enhancement

#169 Use case-insensitive sorting for rules, configs, and lists
  lib/configs.ts
  lib/rule-list.ts
  test/lib/__snapshots__/generator-test.ts.snap
  test/lib/generator-test.ts
Labels: bug

#170 Use code-style around rule name in rule doc title only when description also present
  lib/rule-notices.ts
  test/lib/__snapshots__/generator-test.ts.snap
Labels: bug

#172 Use actual nbsp character instead of HTML entity when avoiding wrapping rule names in rules list
  lib/rule-list-columns.ts
  test/lib/__snapshots__/generator-test.ts.snap
Labels: bug

#175 Use correct rule doc title format fallback when rule missing description
  lib/rule-notices.ts
  test/lib/__snapshots__/generator-test.ts.snap
  test/lib/generator-test.ts
Labels: bug

#176 Check for escaped version of option name in rule doc
  lib/generator.ts
  test/lib/generator-test.ts
Labels: bug

#177 Throw error when trying to use general configs emoji for a config when multiple configs are present
  lib/configs.ts
  test/lib/__snapshots__/generator-test.ts.snap
  test/lib/generator-test.ts
Labels: bug

#178 Add option `--rule-doc-section-options`
  README.md
  lib/cli.ts
  lib/generator.ts
  test/lib/generator-test.ts
Labels: enhancement

#180 Indicate which configs warn for a rule
  README.md
  lib/rule-notices.ts
  lib/types.ts
  test/lib/__snapshots__/generator-test.ts.snap
  test/lib/generator-test.ts
Labels: enhancement

#183 Mention popular plugins that use this
  README.md
Labels: documentation

#187 Show diff when docs out-of-sync with `--check`
  lib/generator.ts
  package-lock.json
  package.json
  test/lib/__snapshots__/generator-test.ts.snap
  test/lib/generator-test.ts
Labels: enhancement

#188 Remove prettier formatting of outputted markdown
  lib/generator.ts
  lib/markdown.ts
  lib/rule-list.ts
  package-lock.json
  package.json
  test/lib/__snapshots__/generator-test.ts.snap
  test/lib/generator-test.ts
Labels: bug

#190 Encourage complementary use of `eslint-plugin/require-meta-docs-description` lint rule in readme
  README.md
Labels: documentation
