Repository bmish/eslint-doc-generator, pull requests merged in 2022-11, with the labels that each got.

#198 Indicate when a rule is set to off/warn by a config in the README rules list
  README.md
  lib/configs.ts
  lib/emojis.ts
  lib/legend.ts
  lib/rule-list.ts
  lib/rule-notices.ts
  lib/types.ts
  test/lib/__snapshots__/generator-test.ts.snap
  test/lib/generator-test.ts
Labels: enhancement

#199 Add default emoji for TypeScript configs, adjust default emoji for accessibility configs
  lib/emojis.ts
Labels: enhancement

#200 Demonstrage usage with a build step or prettier formatting
  README.md
Labels: documentation

#201 Ensure notation for config that warns/disables a rule does not wrap to separate line
  README.md
  lib/configs.ts
  lib/rule-list.ts
  test/lib/__snapshots__/generator-test.ts.snap
Labels: bug

#203 Redo fix to ensure notation for config that warns/disables a rule does not wrap to separate line in rules table cell
  README.md
  lib/configs.ts
  lib/rule-list.ts
  lib/types.ts
  test/lib/__snapshots__/generator-test.ts.snap
Labels: bug

#205 Redesign information architecture of rules table columns and rule doc notices for representing rule configs/severities
  README.md
  lib/configs.ts
  lib/emojis.ts
  lib/legend.ts
  lib/rule-list-columns.ts
  lib/rule-list.ts
  lib/rule-notices.ts
  lib/types.ts
  test/lib/__snapshots__/generator-test.ts.snap
  test/lib/generator-test.ts
Labels: breaking

#208 Move examples into separate files
  README.md
  docs/examples/eslint-plugin-test/README.md
  docs/examples/eslint-plugin-test/docs/rules/no-foo.md
  docs/examples/eslint-plugin-test/docs/rules/prefer-bar.md
  docs/examples/eslint-plugin-test/docs/rules/require-baz.md
Labels: documentation

#218 Fix deprecated rule replacement rule link when plugin prefix included in replacement rule name
  lib/rule-notices.ts
  test/lib/__snapshots__/generator-test.ts.snap
  test/lib/generator-test.ts
Labels: bug

#220 Fix deprecated rule replacement rule link with nested rule names
  lib/rule-notices.ts
  test/lib/__snapshots__/generator-test.ts.snap
  test/lib/generator-test.ts
Labels: bug

#221 Add CodeQL
  .github/workflows/codeql.yml
Labels: internal

#222 Add `--path-rule-doc` and `--path-rule-list` options
  README.md
  lib/cli.ts
  lib/generator.ts
  lib/package-json.ts
  lib/rule-list.ts
  test/lib/__snapshots__/generator-test.ts.snap
  test/lib/generator-test.ts
Labels: enhancement

#223 Implement config file support
  README.md
  bin/eslint-doc-generator.ts
  lib/cli.ts
  lib/configs.ts
  lib/generator.ts
  lib/option-parsers.ts
  lib/options.ts
  lib/rule-doc-title-format.ts
  lib/rule-list-columns.ts
  lib/rule-notices.ts
  package-lock.json
  package.json
  test/lib/__snapshots__/cli-test.ts.snap
  test/lib/cli-test.ts
  test/lib/generator-test.ts
Labels: enhancement

#229 Add optional rule list column `fixableAndHasSuggestions`
  README.md
  lib/legend.ts
  lib/options.ts
  lib/rule-list-columns.ts
  lib/rule-list.ts
  lib/types.ts
  test/lib/__snapshots__/generator-test.ts.snap
  test/lib/generator-test.ts
Labels: enhancement

#230 Remove special case handling for rule doc notice `fixableAndHasSuggestions`
  README.md
  lib/cli.ts
  lib/options.ts
  lib/rule-notices.ts
Labels: bug

#232 Add optional column and notice to indicate whether a rule is configurable
  README.md
  docs/examples/eslint-plugin-test/README.md
  docs/examples/eslint-plugin-test/docs/rules/no-foo.md
  docs/examples/eslint-plugin-test/docs/rules/prefer-bar.md
  docs/examples/eslint-plugin-test/docs/rules/require-baz.md
  lib/emojis.ts
  lib/legend.ts
  lib/options.ts
  lib/rule-list-columns.ts
  lib/rule-list.ts
  lib/rule-notices.ts
  lib/types.ts
  test/lib/__snapshots__/generator-test.ts.snap
  test/lib/generator-test.ts
Labels: enhancement

#141 More robust loading of CJS plugins using `require()`
  lib/package-json.ts
  test/fixtures/cjs-config-extends/README.md
  test/fixtures/cjs-config-extends/base-base-base-config.cjs
  test/fixtures/cjs-config-extends/base-base-config.cjs
  test/fixtures/cjs-config-extends/base-config.cjs
  test/fixtures/cjs-config-extends/docs/rules/no-bar.md
  test/fixtures/cjs-config-extends/docs/rules/no-baz.md
  test/fixtures/cjs-config-extends/docs/rules/no-biz.md
  test/fixtures/cjs-config-extends/docs/rules/no-foo.md
  test/fixtures/cjs-config-extends/index.cjs
  test/fixtures/cjs-config-extends/override-config.cjs
  test/fixtures/cjs-config-extends/package.json
  test/fixtures/cjs-main-directory/README.md
  test/fixtures/cjs-main-directory/lib/index.cjs
  test/fixtures/cjs-main-directory/package.json
  test/fixtures/cjs-main-file-does-not-exist/README.md
  test/fixtures/cjs-main-file-does-not-exist/package.json
  test/fixtures/cjs-missing-main/README.md
  test/fixtures/cjs-missing-main/index.cjs
  test/fixtures/cjs-missing-main/package.json
  test/fixtures/cjs/README.md
  test/fixtures/cjs/docs/rules/no-foo.md
  test/fixtures/cjs/index.cjs
  test/fixtures/cjs/package.json
  test/lib/__snapshots__/generate-cjs-test.ts.snap
  test/lib/__snapshots__/generator-test.ts.snap
  test/lib/generate-cjs-test.ts
  test/lib/generator-test.ts
Labels: enhancement

#233 Target `ES2020` for TypeScript output
  tsconfig.json
Labels: bug

#234 Support absolute path for plugin root CLI argument
  lib/package-json.ts
  test/lib/generator-test.ts
Labels: bug

#239 Split up tests into multiple test files
  jest.config.cjs
  test/lib/__snapshots__/generator-test.ts.snap
  test/lib/generate/__snapshots__/check-test.ts.snap
  test/lib/generate/__snapshots__/cjs-test.ts.snap
  test/lib/generate/__snapshots__/comment-markers-test.ts.snap
  test/lib/generate/__snapshots__/config-emoji-test.ts.snap
  test/lib/generate/__snapshots__/configs-test.ts.snap
  test/lib/generate/__snapshots__/deprecated-rule-test.ts.snap
  test/lib/generate/__snapshots__/file-paths-test.ts.snap
  test/lib/generate/__snapshots__/general-test.ts.snap
  test/lib/generate/__snapshots__/package-json-test.ts.snap
  test/lib/generate/__snapshots__/rule-description-test.ts.snap
  test/lib/generate/__snapshots__/rule-doc-notices-test.ts.snap
  test/lib/generate/__snapshots__/rule-doc-title-format-test.ts.snap
  test/lib/generate/__snapshots__/rule-list-columns-test.ts.snap
  test/lib/generate/__snapshots__/rule-list-split-by-test.ts.snap
  test/lib/generate/__snapshots__/rule-metadata-test.ts.snap
  test/lib/generate/__snapshots__/rule-options-test.ts.snap
  test/lib/generate/__snapshots__/rule-type-test.ts.snap
  test/lib/generate/__snapshots__/sorting-test.ts.snap
  test/lib/generate/__snapshots__/url-configs-test.ts.snap
  test/lib/generate/check-test.ts
  test/lib/generate/cjs-test.ts
  test/lib/generate/comment-markers-test.ts
  test/lib/generate/config-emoji-test.ts
  test/lib/generate/configs-test.ts
  test/lib/generate/deprecated-rule-test.ts
  test/lib/generate/file-paths-test.ts
  test/lib/generate/general-test.ts
  test/lib/generate/package-json-test.ts
  test/lib/generate/rule-description-test.ts
  test/lib/generate/rule-doc-notices-test.ts
  test/lib/generate/rule-doc-section-test.ts
  test/lib/generate/rule-doc-title-format-test.ts
  test/lib/generate/rule-list-columns-test.ts
  test/lib/generate/rule-list-split-by-test.ts
  test/lib/generate/rule-metadata-test.ts
  test/lib/generate/rule-options-test.ts
  test/lib/generate/rule-type-test.ts
  test/lib/generate/sorting-test.ts
  test/lib/generate/url-configs-test.ts
  test/lib/generator-test.ts
Labels: internal

#240 Add option `--init-rule-docs`
  README.md
  lib/cli.ts
  lib/generator.ts
  lib/options.ts
  test/lib/__snapshots__/cli-test.ts.snap
  test/lib/cli-test.ts
  test/lib/generate/__snapshots__/file-paths-test.ts.snap
  test/lib/generate/file-paths-test.ts
Labels: enhancement

#243 Add test code coverage badge
  README.md
Labels: documentation

#241 Ensure tests are type-checked but not published
  package.json
  tsconfig.build.json
  tsconfig.json
Labels: internal

#249 Use TypeScript `satisfies` operator for option defaults
  lib/options.ts
Labels: internal

#251 Add test that external rules are ignored
  test/lib/generate/__snapshots__/configs-test.ts.snap
  test/lib/generate/configs-test.ts
Labels: internal

#256 Add test for variation of scoped plugin name
  lib/package-json.ts
  test/lib/generate/__snapshots__/package-json-test.ts.snap
  test/lib/generate/package-json-test.ts
Labels: internal

#259 Add prefix to link name for readme config badge
  README.md
  lib/configs.ts
  test/lib/generate/__snapshots__/config-emoji-test.ts.snap
  test/lib/generate/__snapshots__/configs-test.ts.snap
  test/lib/generate/__snapshots__/sorting-test.ts.snap
  test/lib/generate/__snapshots__/url-configs-test.ts.snap
Labels: breaking

#262 Add new option `--url-rule-doc`
  README.md
  lib/cli.ts
  lib/generator.ts
  lib/options.ts
  lib/rule-list.ts
  lib/rule-notices.ts
  test/lib/__snapshots__/cli-test.ts.snap
  test/lib/cli-test.ts
  test/lib/generate/__snapshots__/url-configs-test.ts.snap
  test/lib/generate/__snapshots__/url-rule-doc-test.ts.snap
  test/lib/generate/url-configs-test.ts
  test/lib/generate/url-rule-doc-test.ts
Labels: enhancement

#263 Reorganize files and functions
  lib/cli.ts
  lib/comment-markers.ts
  lib/generator.ts
  lib/options.ts
  lib/package-json.ts
  lib/plugin-config-resolution.ts
  lib/plugin-configs.ts
  lib/rule-doc-notices.ts
  lib/rule-list-columns.ts
  lib/rule-list-legend.ts
  lib/rule-list.ts
  lib/types.ts
  test/lib/cli-test.ts
  test/lib/generate/__snapshots__/option-check-test.ts.snap
  test/lib/generate/__snapshots__/option-config-emoji-test.ts.snap
  test/lib/generate/__snapshots__/option-rule-doc-notices-test.ts.snap
  test/lib/generate/__snapshots__/option-rule-doc-title-format-test.ts.snap
  test/lib/generate/__snapshots__/option-rule-list-columns-test.ts.snap
  test/lib/generate/__snapshots__/option-rule-list-split-by-test.ts.snap
  test/lib/generate/__snapshots__/option-url-configs-test.ts.snap
  test/lib/generate/__snapshots__/option-url-rule-doc-test.ts.snap
  test/lib/generate/__snapshots__/rule-deprecation-test.ts.snap
  test/lib/generate/option-check-test.ts
  test/lib/generate/option-config-emoji-test.ts
  test/lib/generate/option-rule-doc-notices-test.ts
  test/lib/generate/option-rule-doc-section-test.ts
  test/lib/generate/option-rule-doc-title-format-test.ts
  test/lib/generate/option-rule-list-columns-test.ts
  test/lib/generate/option-rule-list-split-by-test.ts
  test/lib/generate/option-url-configs-test.ts
  test/lib/generate/option-url-rule-doc-test.ts
  test/lib/generate/rule-deprecation-test.ts
Labels: internal

#264 Export type for config file
  README.md
  lib/index.ts
  package.json
Labels: enhancement

#269 Allow content above rule doc title
  lib/generator.ts
  lib/markdown.ts
  test/lib/generate/__snapshots__/comment-markers-test.ts.snap
  test/lib/generate/comment-markers-test.ts
  test/lib/generate/configs-test.ts
Labels: enhancement

#270 Allow specifying multiple rules lists with `--path-rule-list`
  README.md
  lib/cli.ts
  lib/comment-markers.ts
  lib/generator.ts
  lib/rule-list.ts
  lib/types.ts
  test/lib/__snapshots__/cli-test.ts.snap
  test/lib/cli-test.ts
  test/lib/generate/__snapshots__/file-paths-test.ts.snap
  test/lib/generate/file-paths-test.ts
  test/lib/generate/option-check-test.ts
Labels: enhancement

#271 Use correct header level when splitting rules list into sub-lists with `--split-by`
  lib/markdown.ts
  lib/rule-list.ts
  test/lib/generate/__snapshots__/option-rule-list-split-by-test.ts.snap
  test/lib/generate/option-rule-list-split-by-test.ts
Labels: enhancement

#275 Fix rule links when specifying a rule list file in a subdirectory with `--path-rule-list`
  lib/generator.ts
  lib/options.ts
  lib/rule-doc-notices.ts
  lib/rule-link.ts
  lib/rule-list.ts
  lib/string.ts
  test/lib/generate/__snapshots__/file-paths-test.ts.snap
  test/lib/generate/file-paths-test.ts
Labels: bug

#280 Fix default rules list path of `README.md`
  lib/generator.ts
  test/lib/generate/__snapshots__/file-paths-test.ts.snap
  test/lib/generate/file-paths-test.ts
Labels: bug

#278 Enable unicode regexp flag
  .eslintrc.cjs
  lib/generator.ts
  lib/markdown.ts
  lib/rule-doc-notices.ts
  lib/rule-link.ts
  lib/rule-list.ts
Labels: internal

#281 ci: check TypeScript with CodeQL
  .github/workflows/codeql.yml
Labels: internal

#282 ci: harden workflows
  .github/workflows/ci.yml
  .github/workflows/codeql.yml
Labels: internal

#283 chore: add empty `prettier` config
  .prettierrc.json
Labels: internal

#279 Ensure deprecated rule replacement link respects `--path-rule-doc`
  lib/generator.ts
  lib/rule-doc-notices.ts
  lib/rule-link.ts
  lib/rule-list.ts
  lib/string.ts
  test/lib/generate/__snapshots__/rule-deprecation-test.ts.snap
  test/lib/generate/rule-deprecation-test.ts
Labels: bug

#287 test: require full function coverage
  jest.config.cjs
Labels: internal

#286 fix: remove extra closing quote from error message
  lib/rule-list.ts
Labels: bug

#285 Add `postprocess` config file option (useful for applying prettier formatting)
  README.md
  lib/cli.ts
  lib/generator.ts
  lib/options.ts
  lib/types.ts
  test/lib/cli-test.ts
  test/lib/generate/__snapshots__/option-postprocess-test.ts.snap
  test/lib/generate/option-postprocess-test.ts
Labels: enhancement

#296 Always display plugin prefix in deprecated rule replacement rule name
  docs/examples/eslint-plugin-test/docs/rules/require-baz.md
  lib/rule-doc-notices.ts
  lib/rule-link.ts
  lib/rule-list.ts
  test/lib/generate/__snapshots__/option-url-rule-doc-test.ts.snap
  test/lib/generate/__snapshots__/rule-deprecation-test.ts.snap
Labels: enhancement

#298 fix: correct path to types
  package.json
Labels: bug

#299 Add JSDocs for exported `GenerateOptions` type
  README.md
  lib/cli.ts
  lib/types.ts
Labels: documentation

#300 Use arrays instead of CSV strings for config file types
  lib/cli.ts
  lib/generator.ts
  lib/option-parsers.ts
  lib/options.ts
  lib/types.ts
  test/lib/__snapshots__/cli-test.ts.snap
  test/lib/cli-test.ts
  test/lib/generate/configs-test.ts
  test/lib/generate/option-config-emoji-test.ts
  test/lib/generate/option-rule-doc-notices-test.ts
  test/lib/generate/option-rule-list-columns-test.ts
  test/lib/generate/rule-options-test.ts
  test/lib/generate/rule-type-test.ts
Labels: breaking

#301 Rename `--split-by` option to `--rule-list-split`
  README.md
  lib/cli.ts
  lib/generator.ts
  lib/options.ts
  lib/rule-list.ts
  lib/types.ts
  test/lib/__snapshots__/cli-test.ts.snap
  test/lib/cli-test.ts
  test/lib/generate/__snapshots__/option-rule-list-split-test.ts.snap
  test/lib/generate/option-rule-list-split-test.ts
Labels: breaking

#303 Use `readonly` for external/array types
  lib/cli.ts
  lib/generator.ts
  lib/option-parsers.ts
  lib/package-json.ts
  lib/plugin-config-resolution.ts
  lib/plugin-configs.ts
  lib/rule-doc-notices.ts
  lib/rule-list-columns.ts
  lib/rule-list-legend.ts
  lib/rule-list.ts
  lib/rule-options.ts
  lib/types.ts
  test/lib/cli-test.ts
Labels: bug

#309 Fully utilize `readonly` modifier for nested array types
  lib/cli.ts
  lib/option-parsers.ts
  lib/types.ts
Labels: bug

#313 Avoid recreating read-only array when passing to markdown-table
  lib/rule-list.ts
  package-lock.json
  package.json
Labels: internal

#312 Add semantic versioning policy
  README.md
Labels: documentation
