Repository bmish/eslint-doc-generator, pull requests merged in 2023-11, with the labels that each got.

#498 Handle when an option could have multiple types in rule options lists
  lib/rule-options-list.ts
  lib/rule-options.ts
  test/lib/generate/__snapshots__/rule-options-list-test.ts.snap
  test/lib/generate/rule-options-list-test.ts
  test/lib/rule-options-test.ts
Labels: bug

#500 Deprecate README-defined badges
  README.md
  lib/cli.ts
  lib/types.ts
Labels: documentation

#447 Throw better exception when failing to load plugin
  lib/package-json.ts
  test/lib/generate/cjs-test.ts
Labels: bug

#502 Support a user-defined function for `--path-rule-doc` option
  README.md
  lib/cli.ts
  lib/generator.ts
  lib/rule-doc-notices.ts
  lib/rule-link.ts
  lib/rule-list.ts
  lib/types.ts
  test/lib/generate/__snapshots__/file-paths-test.ts.snap
  test/lib/generate/file-paths-test.ts
Labels: enhancement

#503 Better display of rule option default for array option
  lib/rule-options-list.ts
  test/lib/generate/__snapshots__/rule-options-list-test.ts.snap
  test/lib/generate/rule-options-list-test.ts
Labels: bug
