Repository bmish/eslint-doc-generator, pull requests merged in 2024-12, with the labels that each got.

#577 Use async file access
  lib/cli.ts
  lib/generator.ts
  lib/package-json.ts
Labels: bug

#575 Require Node 18, 20, 22+
  .github/workflows/ci.yml
  jest.config.cjs
  package.json
Labels: breaking

#576 Update to eslint v9 flat config and typescript v5
  .eslintignore
  .eslintrc.cjs
  bin/eslint-doc-generator.ts
  eslint.config.js
  jest.config.ts
  lib/config-format.ts
  lib/config-list.ts
  lib/generator.ts
  lib/option-parsers.ts
  lib/package-json.ts
  lib/plugin-configs.ts
  lib/rule-doc-notices.ts
  lib/rule-doc-title-format.ts
  lib/rule-link.ts
  lib/rule-list-columns.ts
  lib/rule-list.ts
  lib/rule-options-list.ts
  lib/rule-options.ts
  lib/types.ts
  package-lock.json
  package.json
  test/jest.setup.cjs
  test/lib/generate/option-rule-doc-notices-test.ts
  test/lib/generate/option-rule-list-columns-test.ts
  test/lib/generate/option-url-rule-doc-test.ts
  test/lib/rule-options-test.ts
  tsconfig.build.json
  tsconfig.json
Labels: internal

#578 Update dev dependencies and refresh lockfile
  package-lock.json
  package.json
Labels: internal

#581 Use ES2023 target for TypeScript
  tsconfig.json
Labels: internal

#582 Drop support below ESLint v8
  package.json
Labels: breaking

#583 Use top-level await for CLI
  bin/eslint-doc-generator.ts
Labels: internal

#591 Switch to `change-case`
  lib/rule-list.ts
  package-lock.json
  package.json
Labels: internal

#590 Respect EOL character from `.editorconfig`
  lib/config-list.ts
  lib/generator.ts
  lib/markdown.ts
  lib/rule-doc-notices.ts
  lib/rule-list-legend.ts
  lib/rule-list.ts
  lib/rule-options-list.ts
  lib/string.ts
  package-lock.json
  package.json
  test/lib/generate/__snapshots__/editor-config-test.ts.snap
  test/lib/generate/editor-config-test.ts
  test/lib/string-test.ts
Labels: bug

#598 Support ESLint plugins with `"type": "module"` and `main` in package.json
  lib/package-json.ts
  test/lib/generate/package-json-test.ts
Labels: enhancement
