Repository bmish/eslint-doc-generator, pull requests merged in 2025-06, with the labels that each got.

#709 Enable flat configs
  lib/plugin-config-resolution.ts
  test/lib/generate/__snapshots__/configs-test.ts.snap
  test/lib/generate/configs-test.ts
Labels: enhancement

#731 Fix csv spacing for deprecated rule replaced-by list
  lib/rule-doc-notices.ts
  test/lib/generate/__snapshots__/rule-deprecation-test.ts.snap
  test/lib/generate/rule-deprecation-test.ts
Labels: bug

#736 chore: automate releases with release-please
  .github/workflows/release-please.yml
  README.md
  RELEASE.md
  package-lock.json
  package.json
Labels: internal

#737 chore: tweak release-please action config
  .github/workflows/release-please.yml
Labels: internal
